// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFcnOdv-ZI2HHPmR-owamIPJnO1Rwc9Vc',
    appId: '1:972389533276:web:7432255fb07acc01c84899',
    messagingSenderId: '972389533276',
    projectId: 'test-afe6d',
    authDomain: 'test-afe6d.firebaseapp.com',
    databaseURL: 'https://test-afe6d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'test-afe6d.appspot.com',
    measurementId: 'G-DS1S4TTY04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcoE-JP_FryEzxPZwwCeX3NtLLtBt0sB4',
    appId: '1:972389533276:android:0b132d0889ee98c7c84899',
    messagingSenderId: '972389533276',
    projectId: 'test-afe6d',
    databaseURL: 'https://test-afe6d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'test-afe6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFCkOoTwtRMTuofbuCOfxeta9E7zErRCk',
    appId: '1:972389533276:ios:693b09f3f07a5608c84899',
    messagingSenderId: '972389533276',
    projectId: 'test-afe6d',
    databaseURL: 'https://test-afe6d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'test-afe6d.appspot.com',
    iosClientId: '972389533276-i8col62nno0684d1d0l7cojepiafjoo7.apps.googleusercontent.com',
    iosBundleId: 'com.example.speroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFCkOoTwtRMTuofbuCOfxeta9E7zErRCk',
    appId: '1:972389533276:ios:693b09f3f07a5608c84899',
    messagingSenderId: '972389533276',
    projectId: 'test-afe6d',
    databaseURL: 'https://test-afe6d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'test-afe6d.appspot.com',
    iosClientId: '972389533276-i8col62nno0684d1d0l7cojepiafjoo7.apps.googleusercontent.com',
    iosBundleId: 'com.example.speroApp',
  );
}
